source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.4"
gem "sprockets-rails"
gem "pg"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "web-console"
  gem "annotate"
end

gem "parallel", "~> 1.26.3"
gem "sidekiq", "~> 7.3.6"

gem "activerecord-import", "~> 2.0"
